services:
  - type: web
    name: alx-travel-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn alx_travel_app.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: alx-travel-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: alx-travel-redis
          property: connectionString

  - type: redis
    name: alx-travel-redis
    plan: free

databases:
  - name: alx-travel-db
    databaseName: alx_travel_db
    user: alx_travel_user
